[package]
name = "CedraCounter"
version = "1.0.0"
authors = ["Cedra Builders"]

[addresses]
counter = "_"

[dev-addresses]
counter = "0xcafe"

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "main"
subdir = "cedra-framework"

[dev-dependencies]
